# Generated by Django 6.1.1 on 2026-09-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountyImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fips", models.CharField(db_index=True, max_length=5, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                (
                    "severity",
                    models.FloatField(help_text="0-100 AMD damage intensity index"),
                ),
                ("impaired_miles", models.FloatField(blank=True, null=True)),
                (
                    "basis",
                    models.TextField(
                        blank=True, help_text="Watersheds this score is based on"
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "name"],
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("county_fips", models.CharField(blank=True, max_length=5)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("ph", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("dissolved_oxygen", models.FloatField(blank=True, null=True)),
                ("turbidity", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
