# Generated by Django 6.1.1 on 2026-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapview", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stream",
            name="dissolved_oxygen",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="ph",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="turbidity",
        ),
        migrations.AddField(
            model_name="stream",
            name="tds_ppm",
            field=models.FloatField(
                blank=True,
                help_text="Total dissolved solids in parts per million",
                null=True,
                verbose_name="dissolved solids (ppm)",
            ),
        ),
    ]
